name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.QI_SERVER }}
          username: ${{ secrets.QI_USERNAME }}
          password: ${{ secrets.QI_PASSWORD }}
          source: "./"  # プロジェクトのルートディレクトリ
          target: "/tuneup-works.com/public_html/qisystem/"  # サーバー上のディレクトリパス
          rm: true  # 古いファイルを削除
          strip_components: 1
          debug: true  # デバッグモードを有効にする
          exclude: |
            vendor/
            admin/pdf_bat/
            admin/csv_bat/
            phpMyAdmin/
            **/.git
            **/.git/*
            admin_new/pdf_bat/
            admin_new/csv_bat/
